# Default values for besserberg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
