# Default values for besserberg.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
volume:
  name: besserberg-vol
configmap:
  name: besserberg-cm
  key: nginx.conf
  path: nginx.conf
